# Generated by Django 3.2.6 on 2021-08-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('decs', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
