# Generated by Django 3.2.6 on 2021-08-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kst', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='recentproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Upload_Recent_Project')),
            ],
        ),
    ]
